version: '3.8'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_URI=${DATABASE_URI}
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASS}
